--- #YAML:1.0
name:               WWW-CDTV
version:            0.04
abstract:           Get a weekly music ranking from CDTV ( Japanese TV Program )
author:
    - Yusuke Wada <yusuke@kamawada.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    DateTime:             0
    Encode:               0
    HTML::Entities:       0
    LWP::UserAgent:       0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
