--- #YAML:1.0
name:                WWW-CDTV
version:             0.02
abstract:            Get a weekly music ranking from CDTV ( Japanese TV Program )
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    DateTime:                      0
    Encode:                        0
    HTML::Entities:                0
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Yusuke Wada <yusuke@kamawada.com>
